Repository Hello-Kitchen/POS-Front-End, pull requests merged in 2024-06, with the labels that each got.

#5 feat: base de router
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/Components/CategoryButton/CategoryButton.css
  src/Components/CategoryButton/CategoryButton.js
  src/Pages/CategoryList/CategoryList.js
  src/Pages/Dashboard/Dashboard.css
  src/Pages/Dashboard/Dashboard.js
  src/Pages/Layout.js
  src/Pages/Login/Login.css
  src/Pages/Login/Login.js
  src/Pages/PosRouter.js
  src/index.js
  src/logo.svg
Labels: 💥 New feature

#10 feat: base de fonctionnement avec le back-end, mise en place de tailw…
  package-lock.json
  package.json
  src/Components/CategoryButton/CategoryButton.css
  src/Components/CategoryButton/CategoryButton.js
  src/Components/CurrentCommand/CurrentCommand.js
  src/Components/LayoutFooter/LayoutFooter.js
  src/Components/LayoutHeader/LayoutHeader.js
  src/Pages/CategoryList/CategoryList.js
  src/Pages/Dashboard/Dashboard.css
  src/Pages/Dashboard/Dashboard.js
  src/Pages/Layout.js
  src/Pages/Login/Login.js
  src/Pages/Login/Logo_Hello_Kitchen.png
  src/Pages/PosRouter.js
  src/index.css
  src/index.js
  tailwind.config.js
Labels: ☀️ Enhancement, 💥 New feature

#14 12 refactor tailwind page login pos
  .gitignore
  README.md
  package-lock.json
  src/Pages/CategoryList/CategoryList.js
  src/Pages/Dashboard/Dashboard.js
  src/Pages/Login/Login.css
  src/Pages/Login/Login.js
Labels: ☀️ Enhancement

#16 feat: ajout du header modulable ainsi que du footer modulable respons…
  package-lock.json
  package.json
  public/book.jpg
  public/lampe.jpg
  public/new_ticket.jpg
  public/sac.jpg
  public/ticket.jpg
  src/Components/FooterButton/FooterButton.js
  src/Components/LayoutFooter/LayoutFooter.js
  src/Components/LayoutHeader/LayoutHeader.js
  src/Pages/Layout.js
  tailwind.config.js
Labels: 💥 New feature

#18 17 stylisme des commande en cours
  package-lock.json
  package.json
  src/Components/CurrentCommand/CurrentCommand.js
  src/Components/LayoutHeader/LayoutHeader.js
  src/Pages/Layout.js
  tailwind.config.js
Labels: 💥 New feature

#20 fix: modification de la taille des boutons du footer
  src/Components/FooterButton/FooterButton.js
Labels: 🪲 Bug
