Repository Hello-Kitchen/POS-Front-End, pull requests merged in 2024-07, with the labels that each got.

#28 23 pos page encaissement
  package-lock.json
  package.json
  src/Components/Calculator/Calculator.js
  src/Components/CategoryButton/CategoryButton.js
  src/Components/CurrentCommand/CurrentCommand.js
  src/Components/FooterButton/FooterButton.js
  src/Components/LayoutFooter/LayoutFooter.js
  src/Components/LayoutHeader/LayoutHeader.js
  src/Components/ModsPay/ModsPay.js
  src/Components/OptionsPay/OptionsPay.js
  src/Pages/Dashboard/Dashboard.js
  src/Pages/Layout.js
  src/Pages/Pay/Pay.js
  src/Pages/PosRouter.js
  tailwind.config.js
Labels: 💥 New feature

#31 fix: bordure correctement placer pour la separation commande courante…
  src/Components/CurrentCommand/CurrentCommand.js
  src/Pages/PosRouter.js
Labels: 🪲 Bug

#33 24 pos remplissage de la commande en cours + envoie des donnees dans la db
  src/Components/CurrentCommand/CurrentCommand.js
  src/Components/FoodElem/DetailList/DetailList.js
  src/Components/FoodElem/FoodDetail/FoodDetail.js
  src/Components/FoodElem/FoodFooter/FoodFooter.js
  src/Components/FoodElem/Ingredientlist/IngredientList.js
  src/Components/FoodElem/IngredientsButton/IngredientsButton.js
  src/Components/FoodElem/ModifButton/ModifBackButton.js
  src/Components/LayoutFooter/LayoutFooter.js
  src/Pages/FoodDetails/FoodDetails.js
  src/Pages/FoodDetails/FoodLayout.js
  src/Pages/FoodDetails/FoodModif/FoodModif.js
  src/Pages/Layout.js
  src/Pages/PosRouter.js
Labels: ☀️ Enhancement, 💥 New feature

#35 34-retirer-barre-bleue-au-dessus-des-boutons-stop--demander-la-suite
  src/Components/CurrentCommand/CurrentCommand.js
Labels: 🪲 Bug

#37 feat: nouvelle interactivité des boutons de modifications de repas
  src/Components/FoodElem/Ingredientlist/IngredientList.js
  src/Components/FoodElem/IngredientsButton/IngredientsButton.js
  src/Pages/FoodDetails/FoodModif/FoodModif.js
Labels: 💥 New feature

#40 39-gestion-des-commandes-vide
  src/Components/CurrentCommand/CurrentCommand.js
Labels: 🪲 Bug
