Repository Hello-Kitchen/POS-Front-End, pull requests merged in 2025-01, with the labels that each got.

#77 clean: Refacto in a SPA
  src/Components/CategoryButton/CategoryButton.js
  src/Components/CurrentCommand/CurrentCommand.js
  src/Components/FoodButton/FoodButton.js
  src/Components/FoodElem/FoodElem.js
  src/Components/FoodElem/FoodFooter/FoodFooter.js
  src/Components/FoodElem/ModifButton/ModifBackButton.js
  src/Components/FoodElem/ModifButton/ModifButton.js
  src/Components/FoodList/FoodList.js
  src/Pages/CategoryList/CategoryLayout.js
  src/Pages/CategoryList/CategoryList.js
  src/Pages/Dashboard/Dashboard.js
  src/Pages/FoodDetails/FoodDetails.js
  src/Pages/FoodDetails/FoodLayout.js
  src/Pages/FoodDetails/FoodModif/FoodModif.js
  src/Pages/PosRouter.js
  src/__tests__/Components/CategoryButton.test.js
  src/__tests__/Components/FoodElem/FoodFooter.test.js
  src/__tests__/Components/FoodElem/ModifBackButton.test.js
  src/__tests__/Components/FoodElem/ModifButton.test.js
Labels: ☀️ Enhancement, 👨‍🦯 Ignore for release

#78 feat: dynamic loading of categories and foods
  src/Pages/Dashboard/Dashboard.js
Labels: 💥 New feature

#72 71 refacto menu buttons
  public/active-book.jpg
  public/active-lampe.jpg
  public/active-sac.jpg
  public/book.jpg
  public/lampe.jpg
  public/sac.jpg
  src/Components/FooterButton/FooterButton.js
  src/Components/LayoutFooter/LayoutFooter.js
  src/Pages/Layout.js
  src/__tests__/Components/FooterButton.test.js
  src/__tests__/Components/LayoutFooter.test.js
  tailwind.config.js
Labels: ☀️ Enhancement

#79 add: base of note button integration
  src/Components/FoodElem/FoodFooter/FoodFooter.js
  src/Components/FoodElem/Ingredientlist/IngredientList.js
Labels: 💥 New feature

#84 feat: header with back button in a food category
  src/Components/CategoryButton/CategoryButton.js
  src/Components/FoodButton/FoodButton.js
  src/Components/FoodList/FoodList.js
  src/Components/FoodList/FoodListHeader.js
  src/Pages/Dashboard/Dashboard.js
  src/__tests__/Components/FoodListHeader.test.js
Labels: 💥 New feature

#80 62 orders tab
  src/Components/CurrentCommand/CurrentCommand.js
  src/Components/OrdersView/FilterButton.js
  src/Components/OrdersView/OrderRow.js
  src/Components/OrdersView/OrdersView.js
  src/Pages/Layout.js
  src/__tests__/Components/CurrentCommand.test.js
  src/__tests__/Components/FilterButton.test.js
  src/__tests__/Components/OrderRow.test.js
  src/__tests__/Components/OrdersView.test.js
  tailwind.config.js
Labels: 💥 New feature
